#!/usr/bin/env bash
#
# Litebase installer for a fresh Linux server.
#
# Installs the binary, creates a dedicated system user and data directory,
# writes a configuration file with generated secrets, and registers a systemd
# service. Safe to re-run: it will not overwrite an existing configuration or
# regenerate secrets.
#
#   curl -fsSL https://.../install.sh | sudo bash
#   sudo ./install.sh --binary ./litebase

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
DATA_DIR="${DATA_DIR:-/var/lib/litebase}"
CONFIG_DIR="${CONFIG_DIR:-/etc/litebase}"
SERVICE_USER="${SERVICE_USER:-litebase}"
SERVICE_NAME="litebase"
PORT="${PORT:-8090}"
BINARY_SRC=""

info()  { printf '\033[0;34m==>\033[0m %s\n' "$*"; }
warn()  { printf '\033[0;33mwarning:\033[0m %s\n' "$*" >&2; }
fail()  { printf '\033[0;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'USAGE'
Litebase installer

Usage: sudo ./install.sh [options]

Options:
  --binary PATH     Install this already-built binary instead of building
  --port PORT       Port to listen on (default 8090)
  --data-dir DIR    Data directory (default /var/lib/litebase)
  --no-service      Install files but do not create the systemd service
  -h, --help        Show this help

The server listens on 127.0.0.1 by default. Put a TLS-terminating reverse
proxy in front of it before exposing it to the internet.
USAGE
}

NO_SERVICE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --binary)   BINARY_SRC="${2:-}"; shift 2 ;;
    --port)     PORT="${2:-}"; shift 2 ;;
    --data-dir) DATA_DIR="${2:-}"; shift 2 ;;
    --no-service) NO_SERVICE=1; shift ;;
    -h|--help)  usage; exit 0 ;;
    *) fail "unknown option: $1 (try --help)" ;;
  esac
done

[ "$(id -u)" -eq 0 ] || fail "this installer must run as root; try: sudo $0"

# ---- locate or build the binary -------------------------------------------

if [ -z "$BINARY_SRC" ]; then
  if [ -x "./litebase" ]; then
    BINARY_SRC="./litebase"
    info "using the binary in the current directory"
  elif [ -f "./Makefile" ] && command -v go >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    info "building from source"
    make build
    BINARY_SRC="./litebase"
  else
    fail "no binary found. Build one with 'make build', or pass --binary PATH"
  fi
fi

[ -f "$BINARY_SRC" ] || fail "binary not found: $BINARY_SRC"

# ---- service account and directories --------------------------------------

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  info "creating system user $SERVICE_USER"
  # A locked, no-login account: the service never needs an interactive shell.
  useradd --system --home-dir "$DATA_DIR" --shell /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null \
    || adduser --system --home "$DATA_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
else
  info "system user $SERVICE_USER already exists"
fi

info "creating directories"
install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_USER" "$DATA_DIR"
install -d -m 0750 -o root -g "$SERVICE_USER" "$CONFIG_DIR"

info "installing binary to $INSTALL_DIR/litebase"
install -m 0755 "$BINARY_SRC" "$INSTALL_DIR/litebase"

# ---- configuration ---------------------------------------------------------

ENV_FILE="$CONFIG_DIR/litebase.env"

if [ -f "$ENV_FILE" ]; then
  info "keeping the existing configuration at $ENV_FILE"
  ADMIN_PASSWORD=""
else
  info "generating configuration and secrets"

  # Prefer openssl, but fall back to /dev/urandom so the installer works on a
  # minimal image.
  gen_secret() {
    if command -v openssl >/dev/null 2>&1; then
      openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-40
    else
      head -c 48 /dev/urandom | base64 | tr -d '\n/+=' | cut -c1-40
    fi
  }

  ADMIN_PASSWORD="$(gen_secret)"
  ENCRYPTION_KEY="$(gen_secret)"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Litebase configuration, generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Keep this file secret: it holds the backup encryption key. Losing that key
# makes existing encrypted backups unrecoverable.

LITEBASE_ADDR=127.0.0.1:$PORT
LITEBASE_DATA_DIR=$DATA_DIR
LITEBASE_LOG_FORMAT=json
LITEBASE_LOG_LEVEL=info

LITEBASE_ADMIN_EMAIL=admin@localhost
LITEBASE_ADMIN_PASSWORD=$ADMIN_PASSWORD

LITEBASE_BACKUP_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Set both of these once a TLS-terminating reverse proxy is in front.
LITEBASE_SECURE_COOKIES=false
LITEBASE_TRUST_PROXY=false
EOF
  chown root:"$SERVICE_USER" "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
fi

# ---- systemd service -------------------------------------------------------

if [ "$NO_SERVICE" -eq 0 ] && command -v systemctl >/dev/null 2>&1; then
  info "installing the systemd service"
  cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Litebase SQLite database service
Documentation=https://github.com/litebase/litebase
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
EnvironmentFile=$ENV_FILE
ExecStart=$INSTALL_DIR/litebase
Restart=on-failure
RestartSec=5s

# Graceful shutdown: SIGINT drains in-flight requests, and the timeout gives
# the server room to finish a backup in progress.
KillSignal=SIGINT
TimeoutStopSec=60

# Hardening. The data directory is the only path the service may write to.
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
LockPersonality=true
ReadWritePaths=$DATA_DIR

# SQLite plus the HTTP server need a modest file descriptor budget.
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl restart "$SERVICE_NAME"

  sleep 2
  if systemctl is-active --quiet "$SERVICE_NAME"; then
    info "service is running"
  else
    warn "the service did not start; check: journalctl -u $SERVICE_NAME -n 50"
  fi
else
  info "skipping the systemd service"
fi

# ---- summary ---------------------------------------------------------------

cat <<EOF

────────────────────────────────────────────────────────────
 Litebase is installed.

   URL           http://127.0.0.1:$PORT
   Binary        $INSTALL_DIR/litebase
   Data          $DATA_DIR
   Config        $ENV_FILE
EOF

if [ -n "$ADMIN_PASSWORD" ]; then
cat <<EOF

   Sign in with
     Email       admin@localhost
     Password    $ADMIN_PASSWORD

   This password is also in $ENV_FILE. Change it after signing in.
EOF
fi

cat <<EOF

 Useful commands
   systemctl status $SERVICE_NAME
   journalctl -u $SERVICE_NAME -f
   litebase --reset-password admin@localhost

 Before exposing this to the internet, put a TLS-terminating reverse proxy in
 front and set LITEBASE_SECURE_COOKIES=true and LITEBASE_TRUST_PROXY=true.
────────────────────────────────────────────────────────────

EOF
