// Package backup creates, stores, restores and retires database snapshots.
package backup

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/litebase/litebase/internal/database"
	"github.com/litebase/litebase/internal/storage"
)

var (
	ErrBackupNotFound = errors.New("backup not found")
	ErrBackupFailed   = errors.New("backup failed")
)

// Trigger records what caused a backup.
type Trigger string

const (
	TriggerManual    Trigger = "manual"
	TriggerScheduled Trigger = "scheduled"
	// TriggerPreRestore is the safety snapshot taken before a restore.
	TriggerPreRestore Trigger = "pre_restore"
)

// Status is the lifecycle state of a backup record.
type Status string

const (
	StatusPending   Status = "pending"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
)

// Record describes one backup.
type Record struct {
	ID           string     `json:"id"`
	DatabaseID   string     `json:"database_id"`
	DatabaseName string     `json:"database_name"`
	ScheduleID   string     `json:"schedule_id,omitempty"`
	Filename     string     `json:"filename"`
	Provider     string     `json:"provider"`
	RemoteID     string     `json:"remote_id,omitempty"`
	SizeBytes    int64      `json:"size_bytes"`
	Checksum     string     `json:"checksum"`
	Encrypted    bool       `json:"encrypted"`
	Trigger      Trigger    `json:"trigger"`
	Status       Status     `json:"status"`
	Error        string     `json:"error,omitempty"`
	StartedAt    time.Time  `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
}

// Service performs backup and restore operations.
type Service struct {
	mgr     *database.Manager
	storage *storage.Registry
	tempDir string
	encKey  string
	log     *slog.Logger
}

// Options configures the backup service.
type Options struct {
	Manager       *database.Manager
	Storage       *storage.Registry
	TempDir       string
	EncryptionKey string
	Logger        *slog.Logger
}

// NewService builds a backup service.
func NewService(o Options) (*Service, error) {
	if err := os.MkdirAll(o.TempDir, 0o700); err != nil {
		return nil, fmt.Errorf("create temp dir: %w", err)
	}
	log := o.Logger
	if log == nil {
		log = slog.Default()
	}
	return &Service{
		mgr:     o.Manager,
		storage: o.Storage,
		tempDir: o.TempDir,
		encKey:  o.EncryptionKey,
		log:     log,
	}, nil
}

// EncryptionAvailable reports whether a key is configured.
func (s *Service) EncryptionAvailable() bool { return s.encKey != "" }

// Providers lists the configured storage backends.
func (s *Service) Providers() []string { return s.storage.Names() }

// CreateOptions controls one backup run.
type CreateOptions struct {
	Database   string
	Provider   string
	Encrypt    bool
	Trigger    Trigger
	ScheduleID string
}

// Create takes a snapshot of a database and stores it.
//
// The snapshot is produced with "VACUUM INTO", which asks SQLite to write a
// transactionally consistent copy of the database as of a single read
// transaction. That is safe against concurrent writers, unlike copying the
// file, which could capture a torn page or miss committed data still in the
// WAL.
func (s *Service) Create(ctx context.Context, opts CreateOptions) (*Record, error) {
	meta, err := s.mgr.Find(ctx, opts.Database)
	if err != nil {
		return nil, err
	}
	if opts.Trigger == "" {
		opts.Trigger = TriggerManual
	}
	if opts.Provider == "" {
		opts.Provider = "local"
	}
	if opts.Encrypt && s.encKey == "" {
		return nil, ErrNoKey
	}
	provider, err := s.storage.Get(opts.Provider)
	if err != nil {
		return nil, err
	}

	started := time.Now().UTC()
	rec := &Record{
		ID:           database.NewID(),
		DatabaseID:   meta.ID,
		DatabaseName: meta.Name,
		ScheduleID:   opts.ScheduleID,
		Filename:     "",
		Provider:     opts.Provider,
		Encrypted:    opts.Encrypt,
		Trigger:      opts.Trigger,
		Status:       StatusPending,
		StartedAt:    started,
	}
	rec.Filename = backupFilename(meta.Name, started, rec.ID, opts.Encrypt)

	if err := s.insertRecord(ctx, rec); err != nil {
		return nil, err
	}

	if err := s.run(ctx, rec, meta.Name, provider, opts.Encrypt); err != nil {
		rec.Status = StatusFailed
		// The message is stored for the operator; it is generated by our own
		// code paths rather than echoed from a client.
		rec.Error = err.Error()
		if updateErr := s.finishRecord(ctx, rec); updateErr != nil {
			s.log.Error("record backup failure", "error", updateErr, "backup_id", rec.ID)
		}
		s.log.Error("backup failed", "database", meta.Name, "error", err)
		return rec, fmt.Errorf("%w: %v", ErrBackupFailed, err)
	}

	rec.Status = StatusCompleted
	completed := time.Now().UTC()
	rec.CompletedAt = &completed
	if err := s.finishRecord(ctx, rec); err != nil {
		return nil, err
	}
	s.log.Info("backup completed",
		"database", meta.Name, "size", rec.SizeBytes,
		"provider", rec.Provider, "encrypted", rec.Encrypted,
		"duration_ms", completed.Sub(started).Milliseconds())
	return rec, nil
}

// run performs the snapshot, optional encryption and upload.
func (s *Service) run(ctx context.Context, rec *Record, dbName string, provider storage.Provider, encrypt bool) error {
	snapshot, cleanup, err := s.snapshot(ctx, dbName)
	if err != nil {
		return err
	}
	defer cleanup()

	// The checksum covers the plaintext snapshot, so it verifies a restore
	// regardless of whether the stored artefact was encrypted.
	checksum, size, err := checksumFile(snapshot)
	if err != nil {
		return err
	}
	rec.Checksum = checksum

	source, err := os.Open(snapshot)
	if err != nil {
		return err
	}
	defer source.Close()

	if !encrypt {
		obj, err := provider.Put(ctx, rec.Filename, source, size)
		if err != nil {
			return fmt.Errorf("upload backup: %w", err)
		}
		rec.SizeBytes = obj.Size
		rec.RemoteID = obj.RemoteID
		return nil
	}

	// Encryption is streamed through a pipe so a large backup is never held in
	// memory in full.
	pr, pw := io.Pipe()
	go func() {
		err := Encrypt(pw, source, s.encKey)
		pw.CloseWithError(err)
	}()

	obj, err := provider.Put(ctx, rec.Filename, pr, -1)
	if err != nil {
		pr.CloseWithError(err)
		return fmt.Errorf("upload encrypted backup: %w", err)
	}
	rec.SizeBytes = obj.Size
	rec.RemoteID = obj.RemoteID
	return nil
}

// snapshot writes a consistent copy of a database to a temporary file.
func (s *Service) snapshot(ctx context.Context, dbName string) (path string, cleanup func(), err error) {
	h, err := s.mgr.Get(ctx, dbName)
	if err != nil {
		return "", nil, err
	}
	defer h.Release()

	// A unique temporary name, in a directory only this server writes to.
	target := filepath.Join(s.tempDir, "snapshot-"+database.NewID()+".db")
	// VACUUM INTO refuses to overwrite, so a stale file must not be in the way.
	if err := os.Remove(target); err != nil && !os.IsNotExist(err) {
		return "", nil, err
	}
	cleanup = func() {
		os.Remove(target)
	}

	// Checkpointing first keeps the WAL from growing during the snapshot; the
	// snapshot itself is still consistent either way.
	if err := h.Checkpoint(ctx); err != nil {
		s.log.Warn("checkpoint before backup", "database", dbName, "error", err)
	}

	// VACUUM INTO takes a path literal and cannot bind a parameter. The path is
	// generated here from a random id inside our own temp directory, never from
	// user input, and is quoted defensively.
	stmt := "VACUUM INTO " + database.QuoteStringLiteral(target)
	if _, err := h.Writer().ExecContext(ctx, stmt); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("create snapshot: %w", err)
	}

	// Confirm the snapshot is a valid, readable database before it is treated
	// as a usable backup.
	if err := database.VerifySQLiteFile(ctx, target); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("snapshot verification failed: %w", err)
	}
	return target, cleanup, nil
}

// Restore replaces a database with the contents of a backup.
//
// A safety snapshot is taken first, so an operator who restores the wrong
// backup can get back to where they were.
func (s *Service) Restore(ctx context.Context, backupID string) error {
	rec, err := s.Get(ctx, backupID)
	if err != nil {
		return err
	}
	if rec.Status != StatusCompleted {
		return fmt.Errorf("backup %s did not complete and cannot be restored", backupID)
	}
	if rec.DatabaseName == "" {
		return fmt.Errorf("backup %s is not associated with a database", backupID)
	}
	provider, err := s.storage.Get(rec.Provider)
	if err != nil {
		return err
	}

	if _, err := s.mgr.Find(ctx, rec.DatabaseName); err != nil {
		return fmt.Errorf("database %q no longer exists", rec.DatabaseName)
	}
	if _, err := s.Create(ctx, CreateOptions{
		Database: rec.DatabaseName,
		Provider: rec.Provider,
		Encrypt:  rec.Encrypted,
		Trigger:  TriggerPreRestore,
	}); err != nil {
		return fmt.Errorf("could not take a safety snapshot before restoring: %w", err)
	}

	staged, cleanup, err := s.fetchToTemp(ctx, provider, rec)
	if err != nil {
		return err
	}
	defer cleanup()

	// Verify the restored bytes match what was backed up before overwriting a
	// live database with them.
	checksum, _, err := checksumFile(staged)
	if err != nil {
		return err
	}
	if rec.Checksum != "" && checksum != rec.Checksum {
		return fmt.Errorf("the backup file is damaged: its checksum does not match the recorded value")
	}
	if err := database.VerifySQLiteFile(ctx, staged); err != nil {
		return fmt.Errorf("the backup is not a valid SQLite database: %w", err)
	}

	if err := s.mgr.ReplaceFile(ctx, rec.DatabaseName, staged); err != nil {
		return err
	}
	s.log.Info("database restored", "database", rec.DatabaseName, "backup_id", rec.ID)
	return nil
}

// fetchToTemp downloads a backup, decrypting it when necessary.
func (s *Service) fetchToTemp(ctx context.Context, provider storage.Provider, rec *Record) (string, func(), error) {
	reader, err := provider.Get(ctx, rec.Filename)
	if err != nil {
		if errors.Is(err, storage.ErrNotFound) {
			return "", nil, fmt.Errorf("the backup file is missing from %s storage", rec.Provider)
		}
		return "", nil, err
	}
	defer reader.Close()

	target := filepath.Join(s.tempDir, "restore-"+database.NewID()+".db")
	cleanup := func() { os.Remove(target) }

	out, err := os.OpenFile(target, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
	if err != nil {
		return "", nil, err
	}
	defer out.Close()

	if rec.Encrypted {
		if s.encKey == "" {
			cleanup()
			return "", nil, fmt.Errorf("this backup is encrypted but no encryption key is configured")
		}
		if err := Decrypt(out, reader, s.encKey); err != nil {
			cleanup()
			return "", nil, err
		}
	} else if _, err := io.Copy(out, reader); err != nil {
		cleanup()
		return "", nil, err
	}

	if err := out.Sync(); err != nil {
		cleanup()
		return "", nil, err
	}
	return target, cleanup, nil
}

// Open returns a reader for downloading a backup.
//
// An encrypted backup is decrypted on the way out so the operator receives a
// usable database file; that is safe because the request is already
// authenticated as an administrator.
func (s *Service) Open(ctx context.Context, backupID string, decrypt bool) (io.ReadCloser, *Record, error) {
	rec, err := s.Get(ctx, backupID)
	if err != nil {
		return nil, nil, err
	}
	provider, err := s.storage.Get(rec.Provider)
	if err != nil {
		return nil, nil, err
	}
	reader, err := provider.Get(ctx, rec.Filename)
	if err != nil {
		if errors.Is(err, storage.ErrNotFound) {
			return nil, nil, fmt.Errorf("the backup file is missing from %s storage", rec.Provider)
		}
		return nil, nil, err
	}

	if !rec.Encrypted || !decrypt {
		return reader, rec, nil
	}
	if s.encKey == "" {
		reader.Close()
		return nil, nil, fmt.Errorf("this backup is encrypted but no encryption key is configured")
	}

	// Decrypt as the response streams, rather than buffering the whole file.
	pr, pw := io.Pipe()
	go func() {
		defer reader.Close()
		err := Decrypt(pw, reader, s.encKey)
		pw.CloseWithError(err)
	}()
	return pr, rec, nil
}

// Delete removes a backup's artefact and its record.
func (s *Service) Delete(ctx context.Context, backupID string) error {
	rec, err := s.Get(ctx, backupID)
	if err != nil {
		return err
	}
	if provider, err := s.storage.Get(rec.Provider); err == nil {
		if err := provider.Delete(ctx, rec.Filename); err != nil {
			s.log.Warn("delete backup artefact", "backup_id", backupID, "error", err)
		}
	}
	_, err = s.mgr.MetaDB().ExecContext(ctx, `DELETE FROM backups WHERE id = ?`, backupID)
	return err
}

// backupFilename builds a unique, sortable artefact name.
//
// The record id is included because the timestamp only has second resolution:
// two backups of one database within the same second would otherwise share a
// filename, and the second would silently overwrite the first. That is not
// hypothetical — restoring takes a safety snapshot immediately beforehand, so
// without the id it could destroy the very backup being restored.
func backupFilename(dbName string, at time.Time, id string, encrypted bool) string {
	suffix := id
	if len(suffix) > 8 {
		suffix = suffix[:8]
	}
	name := fmt.Sprintf("%s-%s-%s.db", dbName, at.Format("20060102-150405"), suffix)
	if encrypted {
		name += ".enc"
	}
	return name
}

// checksumFile returns the SHA-256 of a file and its size.
func checksumFile(path string) (string, int64, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", 0, err
	}
	defer f.Close()

	h := sha256.New()
	n, err := io.Copy(h, f)
	if err != nil {
		return "", 0, err
	}
	return hex.EncodeToString(h.Sum(nil)), n, nil
}

func (s *Service) insertRecord(ctx context.Context, rec *Record) error {
	var scheduleID any
	if rec.ScheduleID != "" {
		scheduleID = rec.ScheduleID
	}
	_, err := s.mgr.MetaDB().ExecContext(ctx,
		`INSERT INTO backups (id, database_id, database_name, schedule_id, filename, provider,
			remote_id, size_bytes, checksum, encrypted, trigger, status, error, started_at)
		 VALUES (?, ?, ?, ?, ?, ?, '', 0, '', ?, ?, ?, '', ?)`,
		rec.ID, rec.DatabaseID, rec.DatabaseName, scheduleID, rec.Filename, rec.Provider,
		boolToInt(rec.Encrypted), string(rec.Trigger), string(rec.Status),
		database.FormatTime(rec.StartedAt))
	return err
}

func (s *Service) finishRecord(ctx context.Context, rec *Record) error {
	var completed any
	if rec.CompletedAt != nil {
		completed = database.FormatTime(*rec.CompletedAt)
	}
	_, err := s.mgr.MetaDB().ExecContext(ctx,
		`UPDATE backups SET remote_id = ?, size_bytes = ?, checksum = ?, status = ?,
			error = ?, completed_at = ? WHERE id = ?`,
		rec.RemoteID, rec.SizeBytes, rec.Checksum, string(rec.Status),
		truncateError(rec.Error), completed, rec.ID)
	return err
}

// truncateError bounds a stored message so a pathological failure cannot bloat
// the metadata database.
func truncateError(msg string) string {
	const maxLen = 1000
	if len(msg) > maxLen {
		return msg[:maxLen]
	}
	return msg
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

const backupColumns = `id, database_id, database_name, COALESCE(schedule_id, ''), filename,
	provider, remote_id, size_bytes, checksum, encrypted, trigger, status, error,
	started_at, completed_at`

func scanBackup(sc interface{ Scan(...any) error }) (*Record, error) {
	var (
		rec             Record
		encrypted       int
		trigger, status string
		started         string
		completed       sql.NullString
		databaseID      sql.NullString
	)
	if err := sc.Scan(&rec.ID, &databaseID, &rec.DatabaseName, &rec.ScheduleID, &rec.Filename,
		&rec.Provider, &rec.RemoteID, &rec.SizeBytes, &rec.Checksum, &encrypted,
		&trigger, &status, &rec.Error, &started, &completed); err != nil {
		return nil, err
	}
	rec.DatabaseID = database.NullString(databaseID)
	rec.Encrypted = encrypted != 0
	rec.Trigger = Trigger(trigger)
	rec.Status = Status(status)
	rec.StartedAt = database.ParseTime(started)
	if completed.Valid && completed.String != "" {
		t := database.ParseTime(completed.String)
		rec.CompletedAt = &t
	}
	return &rec, nil
}

// Get returns one backup record.
func (s *Service) Get(ctx context.Context, id string) (*Record, error) {
	row := s.mgr.MetaRead().QueryRowContext(ctx,
		`SELECT `+backupColumns+` FROM backups WHERE id = ?`, id)
	rec, err := scanBackup(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrBackupNotFound
	}
	return rec, err
}

// ListOptions filters the backup history.
type ListOptions struct {
	Database string
	Limit    int
	Offset   int
}

// List returns backup history, newest first.
func (s *Service) List(ctx context.Context, opts ListOptions) ([]Record, error) {
	limit := opts.Limit
	if limit <= 0 || limit > 500 {
		limit = 100
	}

	query := `SELECT ` + backupColumns + ` FROM backups`
	args := []any{}
	if opts.Database != "" {
		query += ` WHERE database_name = ?`
		args = append(args, opts.Database)
	}
	query += ` ORDER BY started_at DESC LIMIT ? OFFSET ?`
	args = append(args, limit, max(opts.Offset, 0))

	rows, err := s.mgr.MetaRead().QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []Record{}
	for rows.Next() {
		rec, err := scanBackup(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *rec)
	}
	return out, rows.Err()
}

// Snapshot writes a consistent copy of a database to a temporary file and
// returns its path along with a cleanup function.
//
// It backs the "export database" download, which needs the same consistency
// guarantee as a backup but does not create a backup record.
func (s *Service) Snapshot(ctx context.Context, dbName string) (path string, cleanup func(), err error) {
	return s.snapshot(ctx, dbName)
}
